apiVersion: apps/v1
kind: Deployment
metadata:
  name: mall-demo
  labels:
    k8s.kuboard.cn/layer: svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mall-demo
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mall-demo
    spec:
      initContainers:
        - name: init-skywalking-agent
          image: harbor.kefu.com/test/skywalking-agent:8.1.0
          imagePullPolicy: IfNotPresent
          command:
            - "sh"
            - "-c"
            - "set -ex;mkdir -p /vmskywalking/agent;cp -r /skywalking/agent/* /vmskywalking/agent;"
          volumeMounts:
            - mountPath: /vmskywalking/agent
              name: skywalking-agent
      containers:
        - env:
          - name: JAVA_OPTS
            value: >-
              -Xss256k 
              -Duser.timezone=Asia/Shanghai 
              -Djava.security.egd=file:/dev/./urandom
          - name: AGENT_OPTS
            value: >-
              -Dapp.id=mall-demo
              -javaagent:/opt/skywalking/agent/skywalking-agent.jar
              -Dskywalking.agent.service_name=mall-demo
              -Dskywalking.collector.backend_service=skywalking-oap:11800
              -Dskywalking.trace.ignore_path=/actuator/**,Lettuce/**
          - name: APP_OPTS
            value: >-
              --spring.profiles.active=test
          image: harbor.kefu.com/test/mall-demo:1.0-SNAPSHOT-husx-master-c647c53-11
          imagePullPolicy: IfNotPresent
          name: mall-demo
          ports:
            - containerPort: 8082
              protocol: TCP
          volumeMounts:
            - mountPath: /opt/skywalking/agent
              name: skywalking-agent
      volumes:
        - name: skywalking-agent
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: mall-demo
spec:
  ports:
    - name: http
      port: 8082
      protocol: TCP
      targetPort: 8082
      nodePort: 30302
  selector:
    app: mall-demo
  type: NodePort