apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitor-mall-monitor
  labels:
    k8s.kuboard.cn/layer: monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitor-mall-monitor
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: monitor-mall-monitor
    spec:
      initContainers:
        - name: init-skywalking-agent
          image: harbor.kefu.com/test/skywalking-agent:8.1.0
          imagePullPolicy: IfNotPresent
          command:
            - "sh"
            - "-c"
            - "set -ex;mkdir -p /vmskywalking/agent;cp -r /skywalking/agent/* /vmskywalking/agent;"
          volumeMounts:
            - mountPath: /vmskywalking/agent
              name: skywalking-agent
      containers:
        - env:
            - name: JAVA_OPTS
              value: >-
                -Xss256k 
                -Duser.timezone=Asia/Shanghai 
                -Djava.security.egd=file:/dev/./urandom
            - name: AGENT_OPTS
              value: >-
                -Dapp.id=mall-monitor
                -javaagent:/opt/skywalking/agent/skywalking-agent.jar
                -Dskywalking.agent.service_name=mall-monitor
                -Dskywalking.collector.backend_service=skywalking-oap:11800
                -Dskywalking.trace.ignore_path=/actuator/**,Lettuce/**
            - name: APP_OPTS
              value: >-
                --spring.profiles.active=test
          image: harbor.kefu.com/test/mall-monitor:1.0-SNAPSHOT-husx-master-6faf090-2
          imagePullPolicy: IfNotPresent
          name: mall-monitor
          ports:
            - containerPort: 8101
              protocol: TCP
          volumeMounts:
            - mountPath: /opt/skywalking/agent
              name: skywalking-agent
      volumes:
        - name: skywalking-agent
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: monitor-mall-monitor
spec:
  type: NodePort         # 配置为NodePort，外部可以访问
  ports:
    - name: http
      port: 8101
      protocol: TCP
      targetPort: 8101
      nodePort: 30399     #  NodePort，外部访问的端口
  selector:
    app: monitor-mall-monitor
